### ISSUE TITLE
Evaluate  current meetup organizer resources

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#189] opened 2023-03-27 18:29 UTC
Identify the set of meetup organizer resources and create where gaps exist.

**Comment by samccann** [comment] 2023-03-27 18:30
https://hackmd.io/rmcC3C84TmyoS0UhE_NYkw

**Comment by anweshadas** [comment] 2023-03-29 09:51
Following are the available organizers resources which I found and included them in the toolkit 

1. https://www.ansible.com/community/events/ansible-meetups
2. https://www.ansible.com/logos
3. https://github.com/ansible-community/meetup
4. https://www.meetup.com/topics/ansible/
5. https://github.com/ansible/ambassadors
6. https://www.meetup.com/topics/ansible/all/

Is there any other available docs which I am missing here?  @cybette  @leogallego I am missing anything here?

**Comment by cybette** [comment] 2023-03-30 09:19
Also https://github.com/ansible/community/wiki/Outreach , although the content is probably duplicate of some of the above

**Comment by anweshadas** [comment] 2023-04-05 08:21
We have listed the  current resources as above. Some of the resources are outdated and needs a revamp. Noted them down in the plan. Therefore closing this issue.

**Closed as completed by anweshadas** 2023-04-05 08:21 UTC
