### ISSUE TITLE
Who 'owns' the ansible-project mailing list?

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/community-team#242] opened 2023-06-10 19:23 UTC
See https://groups.google.com/g/ansible-project/c/dIinBr0IhlI/m/SEzql0oQAQAJ - there seems to be no way to contact the 'owners' of the ansible-project mailing list.

Maybe the community team are "the owners"? Or maybe they can figure out who is?

**Comment by sivel** [comment] 2023-06-12 18:03
Largely it is the core team who manages those lists (ansible-project/ansible-devel/ansible-announce), and approves moderated messages, marks them as spam and such.

As far as contacting the owners, is there a problem with just emailing the list?  There is otherwise no public email list that encompasses the owners/managers of the lists.  We can always direct people with questions about the lists to irc/matrix #ansible-devel channel.

As for the email that was mentioned, we see them, but if they come in over the weekend or such it takes a while to react to them if we deem them inappropriate, and it's not impossible they just get missed due to the amount of emails we see every day.

Also, fwiw, reporting a message doesn't notify the group owners/managers afaik.

**Comment by sivel** [comment] 2023-06-12 18:21
BTW, looks like Google Groups supports this by emailing `<group-name>+owner@googlegroups.com`

**Comment by sivel** [comment] 2023-06-12 18:37
fwiw, I've added the owner email address to the description of each list, when viewed through the web browser:

https://groups.google.com/g/ansible-project

**Comment by felixfontein** [comment] 2023-06-12 18:40
> BTW, looks like Google Groups supports this by emailing `<group-name>+owner@googlegroups.com`

@dnmvisser wrote in the post to the list that he wrote a message to "ansible-project+owners@googlegroups.com", but it came back with

> This group does not accept email to owners or managers. To send a
> message to the owner, visit the following page:
> https://groups.google.com/d/contactowner/ansible-project

And then:

> That page redirects to
> https://groups.google.com/g/ansible-project/about, which has no owner
> contact information whatsoever....

(Unfortunately the HTML verison of the mail at https://groups.google.com/g/ansible-project/c/dIinBr0IhlI/m/SEzql0oQAQAJ hides the owner address, I had to look at the copy of the message in my email program to confirm this.)

So adding the `+owners` address there doesn't help.

**Comment by sivel** [comment] 2023-06-12 18:51
I'm not sure if it was a configuration issue, but I tweaked something, and confirmed it works.  You do have to be a member to email it.

I've managed to update the short description, but had to delete other information to include the email address for the owners.

**Comment by dnmvisser** [comment] 2023-06-13 09:14
Hii, I just tried again (to `ansible-project+owners@googlegroups.com`  (plural) and `ansible-project+owner@googlegroups.com` (singular)) but both still bounce. I'm doing this from the very gmail address that I'm subscribed to the list with:

```
Hello [dnmvisser@gmail.com](mailto:dnmvisser@gmail.com),

We received your message to the owner of the group ansible-project.

This group does not accept email to owners or managers. To send a message to the owner, visit the following page: https://groups.google.com/d/contactowner/ansible-project

If you have questions related to this or any other Google Group, visit the Help Center at https://groups.google.com/support/.

Thanks,

Google Groups



----- Original message -----

X-Google-Smtp-Source: ACHHUZ6JQ513BYklFbPIrShvjsHoQiLxYLLVhERt5EPMs3jKyS2/Ah7v+RK242BrdYpaZAb0uSbk
X-Received: by 2002:a17:907:3f83:b0:94f:704d:a486 with SMTP id hr3-20020a1709073f8300b0094f704da486mr12571422ejc.32.1686647202667;
        Tue, 13 Jun 2023 02:06:42 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1686647202; cv=none;
        d=[google.com](http://google.com/); s=arc-20160816;
        b=F1NLkGXEQc4lhyxpP1QS8gHABM8k4czCuL1xKutI2OGmKFeu9ntEqmu+j4VPggSzUd
         4s2hsijlZuy8Xpkq9bVpM50onbUe8LrAOq6EPJoxQf0TrxjLceK5KxAqs42H5AZgw78l
         NnPjzoospONUiylrln1Qls6KP42q5q7Y4uzSdhX+sCo/jU7TS3LDmWhsA/207F2biMl1
         gHgdyUI7UDiNAkqlBHZTJq9de4vYp9mwwQ+s9F9mkOr7HD4t7peY3jhayssVg8Sfgn/9
         KQqBB+49DLrYh1wx8Jboctc2IrJw9Q2pW4ktHjxOifScI3aoTTUfweF/TzV3RsAluNe/
         +9Tg==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=[google.com](http://google.com/); s=arc-20160816;
        h=to:subject:message-id:date:from:mime-version:dkim-signature;
        bh=MwMRp38Cw4l0ImDOQ66OmBXZqPkKz2IoAa/L5fUfNdM=;
        b=r7Z3Qu4XMGyr7m+gbYzwheRYMrWt5CHGmSCoWjWEZhFAVZPpWcr+XfT9/4MutesOtU
         P3cU32GRlU3xDlcso81d35ImpaCaaxmzobhMY9sCbfZpkkNDEJ/erlyx8HHpDypzkPWC
         S/Qftxvv+cgXlf0ftdSuOy+mWD0NfyUp45KuqJEQL75ivx/vHq2SrykTUJt4HACLHttQ
         eVgpjDkazfStCXovH8VMxbIrgv77utGvRnsN6bkaNbz1MrYNtg/xo6B//KVu2Blv9cAQ
         A/Vlny0l4ImAqJfRdugXp1qS/MW6EgDCcvNVrasU0CfqPV275YUOAw6JNJhW6ENkI8gz
         DrYA==
ARC-Authentication-Results: i=1; [gmr-mx.google.com](http://gmr-mx.google.com/);
       dkim=pass header.i=@[gmail.com](http://gmail.com/) header.s=20221208 header.b=l9owsvKR;
       spf=pass ([google.com](http://google.com/): domain of [dnmvisser@gmail.com](mailto:dnmvisser@gmail.com) designates 2a00:1450:4864:20::22a as permitted sender) smtp.mailfrom=[dnmvisser@gmail.com](mailto:dnmvisser@gmail.com);
       dmarc=pass (p=NONE sp=QUARANTINE dis=NONE) header.from=[gmail.com](http://gmail.com/)
Return-Path: <[dnmvisser@gmail.com](mailto:dnmvisser@gmail.com)>
Received: from [mail-lj1-x22a.google.com](http://mail-lj1-x22a.google.com/) ([mail-lj1-x22a.google.com](http://mail-lj1-x22a.google.com/). [2a00:1450:4864:20::22a])
        by [gmr-mx.google.com](http://gmr-mx.google.com/) with ESMTPS id he13-20020a1709073d8d00b00977d096b2f9si641203ejc.2.2023.06.13.02.06.42
        for <[ansible-project+owners@googlegroups.com](mailto:ansible-project%2Bowners@googlegroups.com)>
        (version=TLS1_3 cipher=TLS_AES_128_GCM_SHA256 bits=128/128);
        Tue, 13 Jun 2023 02:06:42 -0700 (PDT)
Received-SPF: pass ([google.com](http://google.com/): domain of [dnmvisser@gmail.com](mailto:dnmvisser@gmail.com) designates 2a00:1450:4864:20::22a as permitted sender) client-ip=2a00:1450:4864:20::22a;
Authentication-Results: [gmr-mx.google.com](http://gmr-mx.google.com/);
       dkim=pass header.i=@[gmail.com](http://gmail.com/) header.s=20221208 header.b=l9owsvKR;
       spf=pass ([google.com](http://google.com/): domain of [dnmvisser@gmail.com](mailto:dnmvisser@gmail.com) designates 2a00:1450:4864:20::22a as permitted sender) smtp.mailfrom=[dnmvisser@gmail.com](mailto:dnmvisser@gmail.com);
       dmarc=pass (p=NONE sp=QUARANTINE dis=NONE) header.from=[gmail.com](http://gmail.com/)
Received: by [mail-lj1-x22a.google.com](http://mail-lj1-x22a.google.com/) with SMTP id 38308e7fff4ca-2b1c30a1653so63513721fa.2
        for <[ansible-project+owners@googlegroups.com](mailto:ansible-project%2Bowners@googlegroups.com)>; Tue, 13 Jun 2023 02:06:42 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=[gmail.com](http://gmail.com/); s=20221208; t=1686647202; x=1689239202;
        h=to:subject:message-id:date:from:mime-version:from:to:cc:subject
         :date:message-id:reply-to;
        bh=MwMRp38Cw4l0ImDOQ66OmBXZqPkKz2IoAa/L5fUfNdM=;
        b=l9owsvKRgGDZVjiJqFYJojfVXwLo6ss7/Y+rd20EI0GgCTwulT0BLbQkUD4fPGfqrS
         GwzwJroaz+36Dhy5mck51PHa6x54A9hJ82pFgm9Nu/XWgby5dPCFIBr2eAhTMVbcNir/
         ymRtZnAbD6MjlJd6SiLrF8VCBLAcVHYM3ZS2h/kDTWULnO+FGEdy44GYBmGr2yL6Lk+J
         ENDBXJ02kqPI6lOA/IFIGVocrZeQJPtg2IT2VfQsq9OCwJUMumatz0MyxS3c3lHtYvjz
         clTa+90T+430QLPmZ7ItYN48DpEjeAuDo4CAUqtFRHlt4U8JlqiJ4+lbr/2cMXjb10z1
         oizw==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=[1e100.net](http://1e100.net/); s=20221208; t=1686647202; x=1689239202;
        h=to:subject:message-id:date:from:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=MwMRp38Cw4l0ImDOQ66OmBXZqPkKz2IoAa/L5fUfNdM=;
        b=jnuyLZ0v3vu1fxRMzFc08FHbaJEOxio5SbXtVGfsKoxo4B3nTK5z0EswpJH2VBrdnH
         PO+2QphrYmvxC/vp5LMK+ICiLmmXniwR3TPxPLYqM2/gEN+/KoxP+MNco69zi1iW/6fl
         oROUXj5IiTBYdZvJc/N3C/EMYwaW4Wom4SkHRvmNLhwptwMpZHMCLMjWKEKfrO0dDpP+
         OtXp0ah8iea7Ebx2pLJg6kTVki8dzkGDdu9Xv8Mds7gIjc4bp/EDz7FJizQtYBMZVCxe
         TPTfLW1jVlxmcwypCfZZoQ6322VF7/Zq1S7NX4CTRB2L4v23YJBlXiYQ7xqtavs/wz1R
         eXzA==
X-Gm-Message-State: AC+VfDzdOajAX0/N/vhZwnyaE6WroL6yG+/ynJUdgXEy7YSDPpUeXPNt
        A26e+FKFfJ3kiTaUF9pbxi1vdbt30AsMWXzpsCjCYQgmuDQ=
X-Received: by 2002:a2e:9f0d:0:b0:2b1:e829:a959 with SMTP id
 u13-20020a2e9f0d000000b002b1e829a959mr3582363ljk.5.1686647201646; Tue, 13 Jun
 2023 02:06:41 -0700 (PDT)
MIME-Version: 1.0
From: Dick Visser <[dnmvisser@gmail.com](mailto:dnmvisser@gmail.com)>
Date: Tue, 13 Jun 2023 11:06:25 +0200
Message-ID: <[CAF8BbLYD62VPtLiX5UZMV-4FdUv7nKfE6GZQ86+mothL-wBTyA@mail.gmail.com](mailto:CAF8BbLYD62VPtLiX5UZMV-4FdUv7nKfE6GZQ86%2BmothL-wBTyA@mail.gmail.com)>
Subject: test
To: [ansible-project+owners@googlegroups.com](mailto:ansible-project%2Bowners@googlegroups.com)
Content-Type: multipart/alternative; boundary="00000000000050ce9605fdff278c"

--00000000000050ce9605fdff278c
Content-Type: text/plain; charset="UTF-8"

does this arrive?

thx for fixing

Dick

--00000000000050ce9605fdff278c
Content-Type: text/html; charset="UTF-8"

<div dir="ltr"><div>does this arrive?</div><div><br></div><div>thx for fixing</div><div><br></div><div>Dick<br></div></div>

--00000000000050ce9605fdff278c--
```

**Comment by sivel** [comment] 2023-06-13 14:22
That is odd, I see you are subscribed, I validated that you are a member, just like my day to day account.

```
Subject: This is a test
From: Matt Martz <matt@sivel.net>
To: ansible-project+owners@googlegroups.com
```

That went through for me. And that email address has no special perms, and matches your account.

**Comment by samccann** [comment] 2024-08-01 19:13
Closing this issue. Please use forum.ansible.com  for further questions

**Closed as completed by samccann** 2024-08-01 19:13 UTC
